---
- name: install apache2 on slaves
  hosts: abcd_target01

  become: true

  tasks:
    - name: update package cache
      apt:
        update_cache: yes

    - name: install apache2
      apt:
        name: apache2
        state: present
