---
- name: install apache2 on slaves
  hosts: tag_name_target01
  become: true

  tasks:
    - name: update package cache
      apt:
        update_cache: yes

    - name: install apache2
      apt:
        name: apache2
        state: present
